name: Backup force-pushed refs
on: [push]

jobs:
  backup_ref:
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: |
          echo forced: ${{ github.event.forced }}
          echo ref: ${{ github.ref }}
          echo before: ${{ github.event.before }}
          echo after: ${{ github.event.after }}
          curl --request POST \
               --url https://api.github.com/repos/${{ github.repository }}/git/refs \
               --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
               --header 'content-type: application/json' \
               --data '{
               "ref": "refs/gh-backup/${{ github.ref }}/${{ github.event.before }}",
               "sha": "${{ github.event.before }}"
               }'
