name: Backup force-pushed refs
on: [push]

jobs:
  backup_ref:
    runs-on: ubuntu-latest
    steps:
      - name: run
        env:
          is_forced: ${{ github.event.forced }}
          previous_sha: ${{ github.event.before }}
        run: |
          echo forced: ${is_forced}
          echo ref: $GITHUB_REF
          echo before: ${previous_sha}
          echo after: $GITHUB_SHA
          curl -f -s -S -o /dev/null \
               --request POST \
               --url https://api.github.com/repos/${GITHUB_REPOSITORY}/git/refs \
               --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
               --header 'content-type: application/json' \
               --data "{
               \"ref\": \"refs/gh-backup/${GITHUB_REF#refs/}/${previous_sha}\",
               \"sha\": \"${previous_sha}\"
               }"
